### PR TITLE
Bugfix/215 end queue design

### PR DESCRIPTION
**Pull request by JNuno007**
Design adapted to Desktop and Mobile
Design updated at the EndQueue and EnQueueSuccess Screens

### CODE REVIEW

**Comment by xicosantos98** [comment]
@JNuno007 since we already have a `yarn.lock` you can remove `package.lock`

**Comment by JNuno007** [comment]
EnQueue Screen Design (Desktop and Mobile)
image
image

**Comment by JNuno007** [comment]
EndQueue Success Screen (Desktop and Design)

image
image

**Comment by xicosantos98** [comment]
image
Faltam assets nos dois menus de mobile @JNuno007

**Comment by JNuno007** [comment]
Fixed Mobile Screens
image
image

**Pull request merged**
